In [1]:
import pandas as pd
import numpy as np


movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [2]:
credits.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [3]:
movies = movies.merge(credits, on='title')

In [4]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [5]:
movies['movie_id'].value_counts

<bound method IndexOpsMixin.value_counts of 0        19995
1          285
2       206647
3        49026
4        49529
         ...
4804      9367
4805     72766
4806    231617
4807    126186
4808     25975
Name: movie_id, Length: 4809, dtype: int64>

In [6]:
movies = movies[['movie_id', 'title', 'overview', 'cast', 'crew', 'genres', 'keywords']]

In [7]:
movies.head(2)

,movie_id,title,overview,cast,crew,genres,keywords
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."

In [8]:
movies['movie_id'].value_counts()

movie_id
72710     2
1255      2
268       2
2661      2
39269     2
         ..
9367      1
72766     1
231617    1
126186    1
25975     1
Name: count, Length: 4803, dtype: int64

In [9]:
movies['title'].value_counts()

title
The Host                                    4
Batman                                      4
Out of the Blue                             4
Avatar                                      1
Pirates of the Caribbean: At World's End    1
                                           ..
El Mariachi                                 1
Newlyweds                                   1
Signed, Sealed, Delivered                   1
Shanghai Calling                            1
My Date with Drew                           1
Name: count, Length: 4800, dtype: int64

In [10]:
movies.tail(2)

,movie_id,title,overview,cast,crew,genres,keywords
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",[],[]
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...","[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224..."

In [11]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
cast        0
crew        0
genres      0
keywords    0
dtype: int64

In [12]:
movies.dropna(inplace=True)

In [13]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
cast        0
crew        0
genres      0
keywords    0
dtype: int64

In [14]:
movies.duplicated().sum()

np.int64(0)

In [15]:
import ast

def convert(text):
    try :
        return ast.literal_eval(text)
    except:
        return []

In [16]:
type(movies['genres'][0])

str

In [17]:
movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)
movies['crew'] = movies['crew'].apply(convert)
movies['cast'] = movies['cast'].apply(convert)

In [18]:
movies.columns

Index(['movie_id', 'title', 'overview', 'cast', 'crew', 'genres', 'keywords'], dtype='str')

In [19]:
movies['crew'] = movies['crew'].apply(convert)
movies['cast'] = movies['cast'].apply(convert)

In [20]:
type(movies['genres'][1])

list

In [21]:
def helper(random):
    L = []
    for i in random:
        L.append(i['name'])
        return L
    


def conver3(obj):
    L = []
    counter = 0
    for i in obj:
        if counter != 3:
            L.append(i['name'])
            counter +=1
        else:
            break
        return L
    

def fetch_director(jb):
    L = []
    for i in jb:
        if i['job'] == 'Director':
            L.append(i['name'])
            break
        return L

In [22]:
movies['genres'] = movies['genres'].apply(convert).apply(helper)
movies['keywords'] = movies['keywords'].apply(convert).apply(helper)
movies['cast'] = movies['cast'].apply(convert).apply(conver3)
movies['crew'] = movies['crew'].apply(convert).apply(fetch_director)

In [23]:
movies.head(2)

,movie_id,title,overview,cast,crew,genres,keywords
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",None,None,None,None
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",None,None,None,None